### ISSUE TITLE
Protesting Facebook dishonesty, Google military projects, or Microsoft ICE projects

### ISSUE THREAD

**Issue by vassudanagunta** [Widdershin/programmers-oath#120]
These have all been in the news. [Google employees have resigned](http://www.foxnews.com/tech/2018/05/14/google-employees-resign-in-protest-over-controversial-pentagon-ai-project-report-says.html) over a Pentagon artificial intelligence contract, and Google has at least backed out a little. Microsoft employees have [protested MS's relationship with ICE](https://www.nytimes.com/2018/06/19/technology/tech-companies-immigration-border.html), yet Microsoft [is making excuses because profits come first](https://www.usatoday.com/story/tech/talkingtech/2018/06/18/microsoft-under-fire-ice-deal-dismayed-family-separations/711755002/). Some high level ex-Facebook employees and execs [have railed out against Facebook](https://www.theguardian.com/technology/2017/dec/11/facebook-former-executive-ripping-society-apart). 

What does this oath have to say about all this? Not the actions of Google, Microsoft or Facebook, but their employees action or lack of action. How many employees kept quiet because the weren't willing to risk being labeled a trouble maker, risk promotions, or quit and give up their high compensation packages?

What about Microsoft's acquisition of GitHub, the de facto home of the open source community. How should users react to GitHub's bait and switch, attracting so many of us on the implied promise of independence and neutrality, but then selling us out for $7.8 billion? Do we allow such actions to go without consequence? Do we ourselves sell out the FOSS movement because GitHub is so comfy for us?

What do signers of this oath think of [these principles](https://gitlab.com/upend/upend.org-content/blob/master/raison-d-etre.md), which would require conscientious programmers to [vote with their feet](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT)?

Many of us lament that Facebook will never be held accountable because at the end of the day, its users don't live their convictions. Aren't we the same, unable to leave this programmer's Facebook?

**Comment by mo-g** [comment]
I mean,

Being Evil (TM) is already proscribed by the oath. So the oath itself has plenty to say.

There's some not-so-great working in your principles, but the intent behind them is good.

But; there's a bigger problem. There's no codipedia commons; you've moved to GitLab, but GitLab is another commercial entity intent on selling it's product. So is Sourceforge (they turned evil a few years ago). Until someone viably creates a wikimedia-esque non-profit, and commits to spending the rest of their life tearing their hair out over funding; we can only ever 'choose our pain'.

Yeah, Microsoft's move isn't great; and like all coders, I'm considering my options. GitLab is only a temporary solution; if all the projects on GitHub move to GitLab, then either they'll turn evil, or someone evil will buy that next. Better to think long-term rather than just join the latest mass migration that sounds good and solves nothing.

**Comment by vassudanagunta** [comment]
> There's some not-so-great working in your principles, but the intent behind them is good.

explain.

> But; there's a bigger problem. There's no codipedia commons; you've moved to GitLab, 

Read [the project's wiki](https://gitlab.com/upend/github/evac-guide/wikis/Why-did-the-project-move-to-GitLab%3F).  GitLab is categorically better than GitHub in terms of principles and #resistance. Not ideal, but better.

> Better to think long-term rather than just join the latest mass migration that sounds good and solves nothing.

Exactly. So why don't you join the project and help?

**Comment by mo-g** [comment]
Describing things as a 'cancer' may sound dramatic, but it's hostile and off-putting. The style of writing is very much along the lines of propaganda (they played us for fools!) which may be your intent or may not, but either way I don't like it. A good argument doesn't need dramatic prose to make; it makes itself. Your target audience is scientists and engineers after all.

Have now read the wiki page you linked. Still don't agree that this is unquestionably the best decision at the present time.

Because everything I've written above. I'm not getting guilt tripped into jumping into the water until I know the smoke in the distance isn't pirates, or a ship that's already on fire. I'm also not splitting my attention between two sites, or giving an unknown (I had literally never heard of GitLab before the Microsoft furore) company my data until I've investigated both it, and my other options.

**Comment by vassudanagunta** [comment]
> Describing things as a 'cancer' may sound dramatic, but it's hostile and off-putting.

> is very much along the lines of propaganda

That's only because you don't agree.  We are talking about values and ethids here. About honesty and doing the right thing. Not about scientific truth or engineering calculations.  I am hostile to advertising, and the advertising "business model" that most of the internet relies on. I think too many "scientists and engineers" in this industry have their salaries paid by advertising to be honest about it.

*"It is difficult to get a man to understand something when his salary depends upon his not understanding it.”*  – Upton Sinclair

**Comment by vassudanagunta** [comment]
@mo-g  Do you realize how many people in this industry would consider the programmers oath "propaganda" if they saw it? Or FOSS?

**Comment by mo-g** [comment]
Sorry, I'm bailing out of this conversation.

_"It's difficult to get **anyone** to do **anything** when you refuse to consider any kind of critical consideration of your proposals"_-@mo-g

**Comment by vassudanagunta** [comment]
I'd love to hear @Widdershin's thoughts. Or that of anyone else who signed the oath.

**Comment by mo-g** [comment]
Person who raised this recanted their oath over two years ago, and no-one else seems to have raised similar concerns, so I'm clicking the close button. It's still in the archive of closed tickets if anyone wants to reference the discussion in the future.
