### ISSUE TITLE
We should semver this, so it is clear, what one is signing

### ISSUE THREAD

**Issue by MoritzFago** [Widdershin/programmers-oath#18]
There is currently a open debate about the contents of this oath. I like the idea of this oath and would like to sign it, but I would want to be safe that it is clear what I signed, just in case, iff the contents change to include something I don't agree.

**Comment by mo-g** [comment]
The signature consists of your github ID and the version (implied by the commit hash) that you wish to sign. This means you can sign the current version, or the older 'non-secular' version, or the next version.

The commit history is more precise and less subject to debate than SemVer - no arguments about whether something is a minor, major or patch fix. You sign a specific version of the text, and resign with an older or newer version if you decide to at a later time.

**Comment by Widdershin** [comment]
This is why we're including a commit hash in our signatures, to show the version of the oath we signed.

SemVer is useful because it provides a convention for communicating the backwards compatibility of a package to users.

I'm not sure that it's incredibly useful to try and bring about the same property here. It could be nice but I feel it will come with a large argument around what can be considered a breaking change in English text, which might be interesting but is beyond the scope of this repository.

Perhaps if there were a versioning system better adapted for our purpose than SemVer, I would be more favourable to adopting it.

**Comment by mo-g** [comment]
Given the complexity of language, and particularly the English language - I'd be tempted to say that any change is a breaking change. I believe this is also generally accepted to be the case for any legal document (you can't 'patch' a contract without agreement from all parties) so I would argue that commit-level versioning is actually the most appropriate choice.

Even something as small as an order-change as proposed in #11 could be seen as a breaking change by some signatories.

**Comment by Thrilleratplay** [comment]
I like this idea but it begs the question, 

> what happens when the terms have been updated and I want to renew my signing?

As software continues to eat the world and hardware advancements create new worlds to consume (the iPhone just recently celebrated its 10 year anniversary and self-driving vehicles as still considered science fiction to many), the ethics of programmers may need to adapt. Consider, what is considered "doing no harm" by doctors [has changes over the years](https://en.wikipedia.org/wiki/Ignaz_Semmelweis) due to advances in science.

**Comment by mo-g** [comment]
@Thrilleratplay Throw up a pull request to replace your hash.

Same goes for if you want to revert to an earlier version.
