### ISSUE TITLE
Suggestion for 10. Be kind to beginners

### ISSUE THREAD

**Issue by abbynormative** [Widdershin/programmers-oath#99]
10. I will be kind to beginning programmers and offer help to the best of my ability. I will not feign surprise when they don't know something, or disparage their code, and will try to point them in the direction of learning to solve their own problems.

**Comment by abbynormative** [comment]
Perhaps there should also be an 11. I will mentor the next generation of programmers and encourage them to follow the Programmer's Oath.

**Comment by Widdershin** [comment]
Good idea! I think there is more generally a missing tenet around how we should treat the people we collaborate with.

There's also a sentiment I'd like to capture around working to improve diversity in our field, perhaps that could be integrated into one of these tenets.

What do you think?

**Comment by manuel-uberti** [comment]
Tenets about kindness towards people we work with and diversity would be great. :+1:

**Comment by abbynormative** [comment]
Agreed on both counts!

**Comment by manuel-uberti** [comment]
Any update on this? :)

**Comment by Widdershin** [comment]
No update right now, in future when I have a block of time free I intend to
make some changes based on this and other issues, just a little swamped
right now.

**Comment by KartikSoneji** [comment]
I too agree that this is a great addition, but feel it should be under a new tenet 11, "Giving back to the community".

This is a first draft, building on @abbynormative 's excellent wording.
Comments and suggestions welcome.
> 11. I will give back to the community by volunteering my time and expertise to open source projects and by offering help to those who need it, without expecting or demanding anything in return.
    I will be kind to my fellow programmers and offer help to the best of my ability. I will not feign surprise when they don't know something, or disparage their code, and will try to point them in the direction of learning to solve their own problems.

In my opinion, "fellow programmers" is a better term than "beginner programmers" since even senior developers may find themselves in a beginner's shoes while learning a new technology or framework.

@Widdershin I will be happy to submit a pull request once everyone is happy with the wording.
